coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080
query.max-memory=1GB
query.max-memory-per-node=512MB
node-scheduler.max-splits-per-node=100
node-scheduler.min-pending-splits-per-task=10

catalog.disabled-catalogs=${ENV:TRINO_DISABLED_CATALOGS}