# This configuration is for applications connecting to Spark services within the container.
# For the master itself, host/port are set via command line or spark-env.sh.
spark.master                     spark://127.0.0.1:7077

# Enable event logging for Spark history server (if you set one up separately)
spark.eventLog.enabled           true
spark.eventLog.dir               file:///tmp/spark-events
spark.history.fs.logDirectory    file:///tmp/spark-events

# For Spark Thrift JDBC/ODBC server
# spark.sql.hive.thriftServer.singleSession  true # Default is true since Spark 3.0

# For Spark Connect client (optional, if clients use these defaults)
# spark.remote sc://127.0.0.1:15002 

spark.driver.host               spark
# spark.jars.packages             org.apache.spark:spark-connect_2.13:3.5.6