connector.name=postgresql
connection-url=jdbc:postgresql://${ENV:POSTGRES_DOCKER_INTERNAL_HOST}:${ENV:POSTGRES_DOCKER_INTERNAL_PORT}/${ENV:POSTGRES_DB}
connection-user=${ENV:POSTGRES_USER}
connection-password=${ENV:POSTGRES_PASSWORD}
