## Update these fields ##
# "endpoint" should be a load-balanced DNS entry or one of the VIPs prefixed by "http://"
# it should not contain a trailing / or anything else.
endpoint=${ENV:VAST_ENDPOINT}
# "data_endpoints" should be be a load-balanced DNS entry or one or more of the VIPs
# prefixed by "http://" it should not contain a trailing / or anything else.
# Multiple VIPs can be used with commas between them, eg: http://x.x.x.x,http://y.y.y.y
data_endpoints=${ENV:VAST_DATA_ENDPOINTS}
# Access and secret keys -- make sure the user was added to an identity policy
# granting them access to the catalog.
access_key_id=${ENV:VAST_ACCESS_KEY}
secret_access_key=${ENV:VAST_SECRET_ACCESS_KEY}
## Don't change these fields ##
connector.name=vast
region=us-east-1
num_of_splits=${ENV:VAST_NUM_OF_SPLITS}
num_of_subsplits=${ENV:VAST_NUM_OF_SUBSPLITS}
vast.http-client.request-timeout=60m
vast.http-client.idle-timeout=60m

# #to change schema delimiter, for example - for SuperSet usage: 
# enable_custom_schema_separator=true
# custom_schema_separator=|
